services:
  db:
    image: postgres:15-alpine
    container_name: leadsmanager-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: leadsmanager_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: leadsmanager-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db

volumes:
  postgres_data:
