# DATA-SOURCE
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA, SQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

# FLYWAY
spring.flyway.enabled=true
spring.flyway.clean-disabled=false
spring.flyway.url=${DB_URL}
spring.flyway.user=${DB_USERNAME}
spring.flyway.password=${DB_PASSWORD}
spring.flyway.locations=classpath:db/migration

# SECURITY
api.security.token.secret=${JWT_SECRET:12345}
