spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
api.security.token.secret=${JWT_SECRET}			

logging.level.org.springframework.web=DEBUG																					
