# DATA-SOURCE
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/leadsmanager_db}
spring.datasource.driverClassName=org.postgresql.Driver

# JPA, SQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

# FLYWAY
spring.flyway.enabled=true
spring.flyway.clean-disabled=false
spring.flyway.locations=classpath:db/migration

# SECURITY
api.security.token.secret=${JWT_SECRET:12345}
