    create table tb_user (
        id bigint generated by default as identity,
        login varchar(255),
        password varchar(255),
        role varchar(255) check ((role in ('ADMIN','COLLABORATOR'))),
        primary key (id)
    )

    create table tb_question (
        id bigint generated by default as identity,
        statement varchar(255),
        primary key (id)
    )

    create table tb_lead (
        total_score integer,
        id bigint generated by default as identity,
        salesman_id bigint,
        email varchar(255),
        lead_classification varchar(255) check ((lead_classification in ('HOT','WARM','COLD','ERROR'))),
        lead_status varchar(255) check ((lead_status in ('NEW','CONTACTED'))),
        name varchar(255),
        phone varchar(255),
        primary key (id)
    )

    create table tb_option (
        weight integer,
        id bigint generated by default as identity,
        question_id bigint,
        description varchar(255),
        primary key (id)
    )

	create table tb_answer (
        recorded_weight integer,
        lead_id bigint not null,
        option_id bigint not null,
        recorded_string varchar(255),
        primary key (lead_id, option_id)
    )

    create table tb_salesman (
        id bigint generated by default as identity,
        last_lead_date timestamp(6) with time zone,
        user_id bigint unique,
        email varchar(255),
        name varchar(255),
        phone varchar(255),
        primary key (id)
    )

    alter table if exists tb_answer 
       add constraint FK5yhpqyclcdk47wjnlfr0qg25j 
       foreign key (option_id) 
       references tb_option
 
    alter table if exists tb_answer 
       add constraint FK9c4ymuoc53pb2bmjraloguvpq 
       foreign key (lead_id) 
       references tb_lead

    alter table if exists tb_lead 
       add constraint FKjjpcn0j5jnl3bmogy386na3oo 
       foreign key (salesman_id) 
       references tb_salesman

    alter table if exists tb_option 
       add constraint FKr2hakcvk66mlqbebr7phfujv2 
       foreign key (question_id) 
       references tb_question

    alter table if exists tb_salesman 
       add constraint FKa5f0bliyl4qxi8n2ic0ldjk6p 
       foreign key (user_id) 
       references tb_user